export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_BURGER_DETAIL = 'SET_BURGER_DETAIL';
export const SET_PAGE_TOTAL = 'SET_PAGE_TOTAL';
export const SET_ITEM_NUM = 'SET_ITEM_NUM';
export const SET_ITEM_BUNS = 'SET_ITEM_BUNS';
export const SET_ITEM_MEAT = 'SET_ITEM_MEAT';
export const SET_ITEM_PRICE = 'SET_ITEM_PRICE';